version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - npm install -g @angular/cli
      - npm cache clear --force
      - cd store && npm install
      - npm update --save
  build:
    commands:
      - ng build --prod --configuration=production
      - aws s3 rm --recursive --exclude "admin/*" s3://spurtcommerce-dev/
      - aws s3 cp dist s3://spurtcommerce-dev/ --recursive
