version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - npm install -g @angular/cli@7.3.4
      - npm cache clear --force
      - cd store && npm install
      - npm update --save
  build:
    commands:
      - npm run dev-build:ssr
      - mv -v scripts/* dist/
      - mv appspec.yml dist/
  artifacts:
    files: 
      - '**/*'
    base-directory: 'dist'

